### ISSUE TITLE
Hello ;-) I don't know if you are still outhere but some help would be appreciated

### ISSUE THREAD

**Issue by Pet1Cable** [jeedom/plugin-sarah#1]
D:\Sarah>SET NODE_PATH=D:\Sarah\NodeJS\node_modules\npm\node_modules;D:\Sarah\No
deJS\node_modules\npm
D:\Sarah>SET NODE_PATH=D:\Sarah\NodeJS\node_modules\npm\node_modules;D:\Sarah\No
deJS\node_modules\npm;D:\Sarah\ExpressJS\node_modules
D:\Sarah>SET NODE_PATH=D:\Sarah\NodeJS\node_modules\npm\node_modules;D:\Sarah\No
deJS\node_modules\npm;D:\Sarah\ExpressJS\node_modules;D:\Sarah\script\lib;D:\Sar
ah\script\vendor

D:\Sarah>"D:\Sarah\NodeJS\node.exe" script/wsrnode.js
info: ==========================================
info:  STARTING WSRNodeJS
info: ==========================================
info: Loading core properties...
info: Loading plugin properties plugins/jeedom/jeedom.prop ...

info: Loading custom properties...
info: initModule:  jeedom
info: Speak remote: initialisation terminé no callback
info: Remote: http://127.0.0.1:8888/?tts=initialisation%20termin%C3%A9
info: Starting task runstop ...
info: Starting CRON Job for runstop at * * * * *
info: Express server listening on port 8080

=======

Plugin "jeedom" for Sarah starting
--------Execute--------
Adresse : http://192.168.1.33/jeedom/core/api/jeeApi.php
-------REQUEST RESULT-------
{"on":false}[{"success":{"/groups/1/action/on":false}}]{"jsonrpc":"2.0","id":"46
67","result":"Action, Done"}
error: Caught exception: SyntaxError: Unexpected token [
    at Object.parse (native)
    at Request._callback (D:\Sarah\plugins\jeedom\jeedom.js:305:32)
    at Request.self.callback (D:\Sarah\NodeJS\node_modules\npm\node_modules\request\index.js:148:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (D:\Sarah\NodeJS\node_modules\npm\node_modules\request\index.js:876:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (D:\Sarah\NodeJS\node_modules\npm\node_modules\request\index.js:827:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)
info: Cron: runstop

The action goes through but then make the all thing collapse.
I can't debug it myself tho I've tried ;-)
Thank for your precious help :-)

In Jeedom.js

        function (err, response, json) {
            if (err || response.statusCode != 200) {
                log.emit('log', 'Error: Callback request');
                log.emit('debugLog', err);
                log.emit('debugLog', response);
                ProcessReturn(false, intCallback);
                return 0;
            }
            log.emit('log', '-------REQUEST RESULT-------');
            log.emit('log', json);
            log.emit('debugLog', '----------------------------');
            ProcessReturn(JSON.parse(json), intCallback);
            return 0;

**Comment by zoic21** [comment]
Hi,
Can you ask for this issue on forum ? Unfortunetly I don't use S.A.R.A.H anymore....
